version: "3.9"

services:
  homeassistant:
  container_name: homeassistant
  image: "homeassistant/home-assistant:latest"
  volumes:
  - ./homeassistant:/config
  - /etc/localtime:/etc/localtime:ro
  restart: unless-stopped
  privileged: true
  ports:
  - "8123:8123"
  mosquitto:
    container_name: mqtt
    image: eclipse-mosquitto
    ports:
    - "1883:1883"
    - "9001:9001"
    volumes:
    - ./mosquitto/config:/mosquitto/config
    - ./mosquitto/data:/mosquitto/data
    - ./mosquitto/log:/mosquitto/log
  zigbee2mqtt:
    container_name: zigbee2mqtt
    depends_on:
    - mosquitto
    image: koenkk/zigbee2mqtt
    volumes:
    - /home/Dev/Docker/zigbee2mqtt/data:/app/data
    - /run/udev:/run/udev:ro
    ports:
    - "8080:8080"
    device:
    - /dev/ttyUSB0:/dev/ttyUSB0
    restart: always
    privileged: true